apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-restapi-deploy
  labels:
    app: python-restapi
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 0
  selector:
    matchLabels:
      app: python-restapi
  template:
    metadata:
      labels:
        app: python-restapi
    spec:
      containers:
      - name: python-restapi
        image: lindynetech/py-rest-app:{{VERSION}}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: pyrest-service
spec:
  type: NodePort
  selector:
    app: python-restapi
  ports:
  - port: 8080
    targetPort: 5000
 

